name: sc-block
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - click
  - pandas
  - elasticsearch=7.17.0
  - phonenumbers
  - country_converter
  - pyyaml
  - transformers
  - fasttext
  - pytorch
